#!/usr/bin/env python3
"""
build.py — scans writings/ for markdown files, reads their Jekyll-style
frontmatter, and generates content.js with everything embedded.

Run this whenever you add, rename, or edit a markdown file:
    python3 build.py

Or build + serve in one shot:
    python3 build.py serve
"""

import json
import re
import sys
from pathlib import Path

ROOT          = Path(__file__).parent
WRITINGS_DIR  = ROOT / "writings"
OUT_FILE      = ROOT / "content.js"

# Visualizations are external URLs — edit this list to add or remove.
VISUALIZATIONS = [
    {"title": "Mode Coupling and Fat Manifolds", "src": "https://kyunghoon-han.github.io/htmls/wobble.html"},
    {"title": "FIMD Sonification", "src": "https://kyunghoon-han.github.io/FIMD_sonification.html"},
    {"title": "Artificial Chemistry on Early Earth", "src": "https://kyunghoon-han.github.io/htmls/artificial_chem_life_early_earth.html"},
]

FRONTMATTER_RE = re.compile(r"^---\s*\n(.*?)\n---\s*\n?", re.DOTALL)
KV_RE          = re.compile(r"^\s*([A-Za-z_][\w\-]*)\s*:\s*(.*?)\s*$")
DATE_FROM_FN   = re.compile(r"^(\d{4})-(\d{2})-(\d{2})")
MD_EXTENSIONS  = {".md", ".markdown"}


def parse_frontmatter(text):
    """Split text into (metadata_dict, body_string)."""
    m = FRONTMATTER_RE.match(text)
    if not m:
        return {}, text
    meta = {}
    for line in m.group(1).splitlines():
        kv = KV_RE.match(line)
        if not kv:
            continue
        key, val = kv.group(1), kv.group(2).strip()
        if len(val) >= 2 and val[0] == val[-1] and val[0] in '"\'':
            val = val[1:-1]
        meta[key] = val
    return meta, text[m.end():].lstrip("\n")


def discover_writings():
    if not WRITINGS_DIR.is_dir():
        return []

    paths = sorted(
        p for p in WRITINGS_DIR.rglob("*")
        if p.is_file() and p.suffix.lower() in MD_EXTENSIONS
    )

    articles = []
    for path in paths:
        try:
            text = path.read_text(encoding="utf-8")
        except Exception as e:
            print(f"  ! skip {path}: {e}", file=sys.stderr)
            continue

        meta, body = parse_frontmatter(text)

        title = meta.get("title") or path.stem
        date  = meta.get("date")
        if not date:
            m = DATE_FROM_FN.match(path.name)
            if m:
                date = f"{m.group(1)}-{m.group(2)}-{m.group(3)}"
        if not date:
            print(f"  ! skip {path}: no date in frontmatter or filename", file=sys.stderr)
            continue

        rel = path.relative_to(ROOT).as_posix()

        entry = {
            "title": title,
            "file":  rel,
            "date":  date,
            "body":  body,
        }
        for key in ("subtitle", "categories", "tags"):
            if meta.get(key):
                entry[key] = meta[key]

        articles.append(entry)
        print(f"  + {date}  {title}")

    articles.sort(key=lambda a: a["date"], reverse=True)
    return articles


def build():
    print(f"Scanning {WRITINGS_DIR.relative_to(ROOT)}/ ...")
    articles = discover_writings()
    content  = {"visualizations": VISUALIZATIONS, "writings": articles}

    payload = json.dumps(content, indent=2, ensure_ascii=False)
    OUT_FILE.write_text(
        "// AUTO-GENERATED by build.py — do not edit by hand.\n"
        "// Re-run `python3 build.py` after changing markdown files.\n"
        f"const CONTENT = {payload};\n",
        encoding="utf-8",
    )
    print(f"\nWrote {OUT_FILE.name} ({len(articles)} article(s)).")


def serve(port=8000):
    import http.server, socketserver
    handler = http.server.SimpleHTTPRequestHandler
    handler.extensions_map[".markdown"] = "text/markdown"
    handler.extensions_map[".md"]       = "text/markdown"
    with socketserver.TCPServer(("", port), handler) as httpd:
        print(f"\nServing at http://localhost:{port}  (Ctrl-C to stop)")
        try:
            httpd.serve_forever()
        except KeyboardInterrupt:
            print("\nStopped.")


if __name__ == "__main__":
    build()
    if len(sys.argv) > 1 and sys.argv[1] == "serve":
        serve()
